/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-02-16 at 22:19:45 UTC 
 * Modify at your own risk.
 */

package com.appspot.rose_hulman_career_fair.careerfair;

/**
 * Service definition for Careerfair (v2).
 *
 * <p>
 * Career Fair API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CareerfairRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Careerfair extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.19.1 of the careerfair library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://rose-hulman-career-fair.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "careerfair/v2/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Careerfair(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Careerfair(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Company collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Careerfair careerfair = new Careerfair(...);}
   *   {@code Careerfair.Company.List request = careerfair.company().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Company company() {
    return new Company();
  }

  /**
   * The "company" collection of methods.
   */
  public class Company {

    /**
     * Create a request for the method "company.delete".
     *
     * This request holds the parameters needed by the careerfair server.  After setting any optional
     * parameters, call the {@link Delete#execute()} method to invoke the remote operation.
     *
     * @param entityKey
     * @return the request
     */
    public Delete delete(java.lang.String entityKey) throws java.io.IOException {
      Delete result = new Delete(entityKey);
      initialize(result);
      return result;
    }

    public class Delete extends CareerfairRequest<com.appspot.rose_hulman_career_fair.careerfair.model.Company> {

      private static final String REST_PATH = "company/delete/{entityKey}";

      /**
       * Create a request for the method "company.delete".
       *
       * This request holds the parameters needed by the the careerfair server.  After setting any
       * optional parameters, call the {@link Delete#execute()} method to invoke the remote operation.
       * <p> {@link
       * Delete#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param entityKey
       * @since 1.13
       */
      protected Delete(java.lang.String entityKey) {
        super(Careerfair.this, "DELETE", REST_PATH, null, com.appspot.rose_hulman_career_fair.careerfair.model.Company.class);
        this.entityKey = com.google.api.client.util.Preconditions.checkNotNull(entityKey, "Required parameter entityKey must be specified.");
      }

      @Override
      public Delete setAlt(java.lang.String alt) {
        return (Delete) super.setAlt(alt);
      }

      @Override
      public Delete setFields(java.lang.String fields) {
        return (Delete) super.setFields(fields);
      }

      @Override
      public Delete setKey(java.lang.String key) {
        return (Delete) super.setKey(key);
      }

      @Override
      public Delete setOauthToken(java.lang.String oauthToken) {
        return (Delete) super.setOauthToken(oauthToken);
      }

      @Override
      public Delete setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Delete) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Delete setQuotaUser(java.lang.String quotaUser) {
        return (Delete) super.setQuotaUser(quotaUser);
      }

      @Override
      public Delete setUserIp(java.lang.String userIp) {
        return (Delete) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String entityKey;

      /**

       */
      public java.lang.String getEntityKey() {
        return entityKey;
      }

      public Delete setEntityKey(java.lang.String entityKey) {
        this.entityKey = entityKey;
        return this;
      }

      @Override
      public Delete set(String parameterName, Object value) {
        return (Delete) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "company.insert".
     *
     * This request holds the parameters needed by the careerfair server.  After setting any optional
     * parameters, call the {@link Insert#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.rose_hulman_career_fair.careerfair.model.Company}
     * @return the request
     */
    public Insert insert(com.appspot.rose_hulman_career_fair.careerfair.model.Company content) throws java.io.IOException {
      Insert result = new Insert(content);
      initialize(result);
      return result;
    }

    public class Insert extends CareerfairRequest<com.appspot.rose_hulman_career_fair.careerfair.model.Company> {

      private static final String REST_PATH = "company/insert";

      /**
       * Create a request for the method "company.insert".
       *
       * This request holds the parameters needed by the the careerfair server.  After setting any
       * optional parameters, call the {@link Insert#execute()} method to invoke the remote operation.
       * <p> {@link
       * Insert#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.rose_hulman_career_fair.careerfair.model.Company}
       * @since 1.13
       */
      protected Insert(com.appspot.rose_hulman_career_fair.careerfair.model.Company content) {
        super(Careerfair.this, "POST", REST_PATH, content, com.appspot.rose_hulman_career_fair.careerfair.model.Company.class);
      }

      @Override
      public Insert setAlt(java.lang.String alt) {
        return (Insert) super.setAlt(alt);
      }

      @Override
      public Insert setFields(java.lang.String fields) {
        return (Insert) super.setFields(fields);
      }

      @Override
      public Insert setKey(java.lang.String key) {
        return (Insert) super.setKey(key);
      }

      @Override
      public Insert setOauthToken(java.lang.String oauthToken) {
        return (Insert) super.setOauthToken(oauthToken);
      }

      @Override
      public Insert setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Insert) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Insert setQuotaUser(java.lang.String quotaUser) {
        return (Insert) super.setQuotaUser(quotaUser);
      }

      @Override
      public Insert setUserIp(java.lang.String userIp) {
        return (Insert) super.setUserIp(userIp);
      }

      @Override
      public Insert set(String parameterName, Object value) {
        return (Insert) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "company.list".
     *
     * This request holds the parameters needed by the careerfair server.  After setting any optional
     * parameters, call the {@link List#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public List list() throws java.io.IOException {
      List result = new List();
      initialize(result);
      return result;
    }

    public class List extends CareerfairRequest<com.appspot.rose_hulman_career_fair.careerfair.model.CompanyCollection> {

      private static final String REST_PATH = "company/list";

      /**
       * Create a request for the method "company.list".
       *
       * This request holds the parameters needed by the the careerfair server.  After setting any
       * optional parameters, call the {@link List#execute()} method to invoke the remote operation. <p>
       * {@link List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected List() {
        super(Careerfair.this, "GET", REST_PATH, null, com.appspot.rose_hulman_career_fair.careerfair.model.CompanyCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public List setAlt(java.lang.String alt) {
        return (List) super.setAlt(alt);
      }

      @Override
      public List setFields(java.lang.String fields) {
        return (List) super.setFields(fields);
      }

      @Override
      public List setKey(java.lang.String key) {
        return (List) super.setKey(key);
      }

      @Override
      public List setOauthToken(java.lang.String oauthToken) {
        return (List) super.setOauthToken(oauthToken);
      }

      @Override
      public List setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (List) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public List setQuotaUser(java.lang.String quotaUser) {
        return (List) super.setQuotaUser(quotaUser);
      }

      @Override
      public List setUserIp(java.lang.String userIp) {
        return (List) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String pageToken;

      /**

       */
      public java.lang.String getPageToken() {
        return pageToken;
      }

      public List setPageToken(java.lang.String pageToken) {
        this.pageToken = pageToken;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.Long limit;

      /**

       */
      public java.lang.Long getLimit() {
        return limit;
      }

      public List setLimit(java.lang.Long limit) {
        this.limit = limit;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.String order;

      /**

       */
      public java.lang.String getOrder() {
        return order;
      }

      public List setOrder(java.lang.String order) {
        this.order = order;
        return this;
      }

      @Override
      public List set(String parameterName, Object value) {
        return (List) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the Linelength collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Careerfair careerfair = new Careerfair(...);}
   *   {@code Careerfair.Linelength.List request = careerfair.linelength().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Linelength linelength() {
    return new Linelength();
  }

  /**
   * The "linelength" collection of methods.
   */
  public class Linelength {

    /**
     * Create a request for the method "linelength.delete".
     *
     * This request holds the parameters needed by the careerfair server.  After setting any optional
     * parameters, call the {@link Delete#execute()} method to invoke the remote operation.
     *
     * @param entityKey
     * @return the request
     */
    public Delete delete(java.lang.String entityKey) throws java.io.IOException {
      Delete result = new Delete(entityKey);
      initialize(result);
      return result;
    }

    public class Delete extends CareerfairRequest<com.appspot.rose_hulman_career_fair.careerfair.model.LineLength> {

      private static final String REST_PATH = "linelength/delete/{entityKey}";

      /**
       * Create a request for the method "linelength.delete".
       *
       * This request holds the parameters needed by the the careerfair server.  After setting any
       * optional parameters, call the {@link Delete#execute()} method to invoke the remote operation.
       * <p> {@link
       * Delete#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param entityKey
       * @since 1.13
       */
      protected Delete(java.lang.String entityKey) {
        super(Careerfair.this, "DELETE", REST_PATH, null, com.appspot.rose_hulman_career_fair.careerfair.model.LineLength.class);
        this.entityKey = com.google.api.client.util.Preconditions.checkNotNull(entityKey, "Required parameter entityKey must be specified.");
      }

      @Override
      public Delete setAlt(java.lang.String alt) {
        return (Delete) super.setAlt(alt);
      }

      @Override
      public Delete setFields(java.lang.String fields) {
        return (Delete) super.setFields(fields);
      }

      @Override
      public Delete setKey(java.lang.String key) {
        return (Delete) super.setKey(key);
      }

      @Override
      public Delete setOauthToken(java.lang.String oauthToken) {
        return (Delete) super.setOauthToken(oauthToken);
      }

      @Override
      public Delete setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Delete) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Delete setQuotaUser(java.lang.String quotaUser) {
        return (Delete) super.setQuotaUser(quotaUser);
      }

      @Override
      public Delete setUserIp(java.lang.String userIp) {
        return (Delete) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String entityKey;

      /**

       */
      public java.lang.String getEntityKey() {
        return entityKey;
      }

      public Delete setEntityKey(java.lang.String entityKey) {
        this.entityKey = entityKey;
        return this;
      }

      @Override
      public Delete set(String parameterName, Object value) {
        return (Delete) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "linelength.insert".
     *
     * This request holds the parameters needed by the careerfair server.  After setting any optional
     * parameters, call the {@link Insert#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.rose_hulman_career_fair.careerfair.model.LineLength}
     * @return the request
     */
    public Insert insert(com.appspot.rose_hulman_career_fair.careerfair.model.LineLength content) throws java.io.IOException {
      Insert result = new Insert(content);
      initialize(result);
      return result;
    }

    public class Insert extends CareerfairRequest<com.appspot.rose_hulman_career_fair.careerfair.model.LineLength> {

      private static final String REST_PATH = "linelength/insert";

      /**
       * Create a request for the method "linelength.insert".
       *
       * This request holds the parameters needed by the the careerfair server.  After setting any
       * optional parameters, call the {@link Insert#execute()} method to invoke the remote operation.
       * <p> {@link
       * Insert#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.rose_hulman_career_fair.careerfair.model.LineLength}
       * @since 1.13
       */
      protected Insert(com.appspot.rose_hulman_career_fair.careerfair.model.LineLength content) {
        super(Careerfair.this, "POST", REST_PATH, content, com.appspot.rose_hulman_career_fair.careerfair.model.LineLength.class);
      }

      @Override
      public Insert setAlt(java.lang.String alt) {
        return (Insert) super.setAlt(alt);
      }

      @Override
      public Insert setFields(java.lang.String fields) {
        return (Insert) super.setFields(fields);
      }

      @Override
      public Insert setKey(java.lang.String key) {
        return (Insert) super.setKey(key);
      }

      @Override
      public Insert setOauthToken(java.lang.String oauthToken) {
        return (Insert) super.setOauthToken(oauthToken);
      }

      @Override
      public Insert setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Insert) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Insert setQuotaUser(java.lang.String quotaUser) {
        return (Insert) super.setQuotaUser(quotaUser);
      }

      @Override
      public Insert setUserIp(java.lang.String userIp) {
        return (Insert) super.setUserIp(userIp);
      }

      @Override
      public Insert set(String parameterName, Object value) {
        return (Insert) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "linelength.list".
     *
     * This request holds the parameters needed by the careerfair server.  After setting any optional
     * parameters, call the {@link List#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public List list() throws java.io.IOException {
      List result = new List();
      initialize(result);
      return result;
    }

    public class List extends CareerfairRequest<com.appspot.rose_hulman_career_fair.careerfair.model.LineLengthCollection> {

      private static final String REST_PATH = "linelength/list";

      /**
       * Create a request for the method "linelength.list".
       *
       * This request holds the parameters needed by the the careerfair server.  After setting any
       * optional parameters, call the {@link List#execute()} method to invoke the remote operation. <p>
       * {@link List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected List() {
        super(Careerfair.this, "GET", REST_PATH, null, com.appspot.rose_hulman_career_fair.careerfair.model.LineLengthCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public List setAlt(java.lang.String alt) {
        return (List) super.setAlt(alt);
      }

      @Override
      public List setFields(java.lang.String fields) {
        return (List) super.setFields(fields);
      }

      @Override
      public List setKey(java.lang.String key) {
        return (List) super.setKey(key);
      }

      @Override
      public List setOauthToken(java.lang.String oauthToken) {
        return (List) super.setOauthToken(oauthToken);
      }

      @Override
      public List setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (List) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public List setQuotaUser(java.lang.String quotaUser) {
        return (List) super.setQuotaUser(quotaUser);
      }

      @Override
      public List setUserIp(java.lang.String userIp) {
        return (List) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String pageToken;

      /**

       */
      public java.lang.String getPageToken() {
        return pageToken;
      }

      public List setPageToken(java.lang.String pageToken) {
        this.pageToken = pageToken;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.Long limit;

      /**

       */
      public java.lang.Long getLimit() {
        return limit;
      }

      public List setLimit(java.lang.Long limit) {
        this.limit = limit;
        return this;
      }

      @com.google.api.client.util.Key
      private java.lang.String order;

      /**

       */
      public java.lang.String getOrder() {
        return order;
      }

      public List setOrder(java.lang.String order) {
        this.order = order;
        return this;
      }

      @Override
      public List set(String parameterName, Object value) {
        return (List) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "linelength.status".
     *
     * This request holds the parameters needed by the careerfair server.  After setting any optional
     * parameters, call the {@link Status#execute()} method to invoke the remote operation.
     *
     * @param companyEntityKey
     * @return the request
     */
    public Status status(java.lang.String companyEntityKey) throws java.io.IOException {
      Status result = new Status(companyEntityKey);
      initialize(result);
      return result;
    }

    public class Status extends CareerfairRequest<com.appspot.rose_hulman_career_fair.careerfair.model.LineLength> {

      private static final String REST_PATH = "linelength/status/{company_entity_key}";

      /**
       * Create a request for the method "linelength.status".
       *
       * This request holds the parameters needed by the the careerfair server.  After setting any
       * optional parameters, call the {@link Status#execute()} method to invoke the remote operation.
       * <p> {@link
       * Status#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param companyEntityKey
       * @since 1.13
       */
      protected Status(java.lang.String companyEntityKey) {
        super(Careerfair.this, "GET", REST_PATH, null, com.appspot.rose_hulman_career_fair.careerfair.model.LineLength.class);
        this.companyEntityKey = com.google.api.client.util.Preconditions.checkNotNull(companyEntityKey, "Required parameter companyEntityKey must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Status setAlt(java.lang.String alt) {
        return (Status) super.setAlt(alt);
      }

      @Override
      public Status setFields(java.lang.String fields) {
        return (Status) super.setFields(fields);
      }

      @Override
      public Status setKey(java.lang.String key) {
        return (Status) super.setKey(key);
      }

      @Override
      public Status setOauthToken(java.lang.String oauthToken) {
        return (Status) super.setOauthToken(oauthToken);
      }

      @Override
      public Status setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Status) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Status setQuotaUser(java.lang.String quotaUser) {
        return (Status) super.setQuotaUser(quotaUser);
      }

      @Override
      public Status setUserIp(java.lang.String userIp) {
        return (Status) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key("company_entity_key")
      private java.lang.String companyEntityKey;

      /**

       */
      public java.lang.String getCompanyEntityKey() {
        return companyEntityKey;
      }

      public Status setCompanyEntityKey(java.lang.String companyEntityKey) {
        this.companyEntityKey = companyEntityKey;
        return this;
      }

      @Override
      public Status set(String parameterName, Object value) {
        return (Status) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Careerfair}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Careerfair}. */
    @Override
    public Careerfair build() {
      return new Careerfair(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CareerfairRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCareerfairRequestInitializer(
        CareerfairRequestInitializer careerfairRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(careerfairRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
